name: ts-publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --global user.email ${{ secrets.git_email }}
          git config --global user.name ${{ secrets.git_name }}
          npm install
          npm run test
          npm run release-publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

